export { default as Calm } from './Trooper.png'
export { default as Death } from './Death.gif'
export { default as Shooting } from './Shooting.gif'
export { default as CoverShooting } from './CoverShooting.gif'
export { default as Test } from './Test.gif'
